name: Docker Images CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  gmssl:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            dkmoonfruit/gmssl:3.1.0
            dkmoonfruit/gmssl:latest
